export const findOneUser = async () => {
  try {
    return;
  } catch(error) {
    throw error;
  }
}